# Most of these are used by kitchen so it can forward them to inspec
output "main_vpc_id" {
  value       = module.main_vpc.vpc_id
  description = "ID of the main VPC geenrated by the module"
}

output "static_assets_bucket_id" {
  value       = aws_s3_bucket.static_assets.bucket
  description = "ID of the bucket serving static assets"
}

output "bastion_sg_id" {
  value       = aws_security_group.bastion.id
  description = "ID of the security group used by the bastion instance"
}

output "bastion_asg_name" {
  value       = module.bastion.asg_name
  description = "ID of the bastion auto scaling group"
}

output "bastion_iam_policy_name" {
  value       = module.bastion.iam_policy_name
  description = "ID of the bastion IAM policy generated by the module"
}

output "bastion_iam_role_name" {
  value       = module.bastion.iam_role_name
  description = "Name of the IAM role/profile generated by the module"
}

output "goiardi_sg_id" {
  value       = aws_security_group.goiardi.id
  description = "ID of the security group used by the goiardi instance"
}

output "goiardi_asg_name" {
  value       = module.goiardi.asg_name
  description = "ID of the goiardi auto scaling group"
}

output "goiardi_iam_policy_name" {
  value       = module.goiardi.iam_policy_name
  description = "ID of the goiardi IAM policy generated by the module"
}

output "goiardi_iam_role_name" {
  value       = module.goiardi.iam_role_name
  description = "Name of the IAM role/profile generated by the module"
}

output "goiardi_extra_iam_policy_name" {
  value       = aws_iam_policy.goiardi.name
  description = "Name of the user defined IAM policy for the goiardi instance"
}

output "main_alb_sg_id" {
  value       = aws_security_group.main_alb.id
  description = "ID of the main ALB's security group"
}

output "main_alb_arn" {
  value = aws_lb.main.arn
  description = "ARN of the main load balancer"
}

output "main_alb_listener_arn" {
  value = aws_lb_listener.main_443.arn
  description = "ARN of the main ALB's HTTPS listener"
}

output "account_availability_zones" {
  value = data.aws_availability_zones.available.names
  description = "A list of all availability zones accessible to your account in the main region"
}

output "main_postgres_sg_id" {
  value       = aws_security_group.main_postgres.id
  description = "ID of the main postgres instance's security group"
}

output "req_db_sg_id" {
  value = aws_security_group.req-db.id
  description = "ID of the security group that allows traffic to the postgres instance"
}
