# Most of these are used by kitchen so it can forward them to inspec
output "main_vpc_id" {
  value       = module.main_vpc.vpc_id
  description = "ID of the main VPC geenrated by the module"
}

output "static_assets_bucket_id" {
  value       = aws_s3_bucket.static_assets.bucket
  description = "ID of the bucket serving static assets"
}

output "bastion_sg_id" {
  value       = aws_security_group.bastion.id
  description = "ID of the security group used by the bastion instance"
}

output "bastion_asg_name" {
  value       = module.bastion.asg_name
  description = "ID of the bastion auto scaling group"
}

output "bastion_iam_policy_name" {
  value       = module.bastion.iam_policy_name
  description = "ID of the bastion IAM policy generated by the module"
}

output "bastion_iam_role_name" {
  value       = module.bastion.iam_role_name
  description = "Name of the IAM role/profile generated by the module"
}

output "account_availability_zones" {
  value = data.aws_availability_zones.available.names
  description = "A list of all availability zones accessible to your account in the main region"
}

output "main_postgres_sg_id" {
  value       = aws_security_group.main_postgres.id
  description = "ID of the main postgres instance's security group"
}

output "req_db_sg_id" {
  value = aws_security_group.req-db.id
  description = "ID of the security group that allows traffic to the postgres instance"
}
