output "goiardi_sg_id" {
  value       = aws_security_group.goiardi.id
  description = "ID of the security group used by the goiardi instance"
}

output "goiardi_asg_name" {
  value       = module.goiardi.asg_name
  description = "ID of the goiardi auto scaling group"
}

output "goiardi_iam_policy_name" {
  value       = module.goiardi.iam_policy_name
  description = "ID of the goiardi IAM policy generated by the module"
}

output "goiardi_iam_role_name" {
  value       = module.goiardi.iam_role_name
  description = "Name of the IAM role/profile generated by the module"
}

output "goiardi_extra_iam_policy_name" {
  value       = aws_iam_policy.goiardi.name
  description = "Name of the user defined IAM policy for the goiardi instance"
}
